#include "world_loader.h"
#include "datagen.h"
#include "types.h"
#include "graph.h"
#include "room.h"

#include <stdlib.h>
#include <string.h>

/* ============================================================
 * Integer compare/destroy callbacks for initializing the graph
 * ============================================================ */

static int compare_ints(const void *a, const void *b) {
    const int *ia = a;
    const int *ib = b;
    if (*ia < *ib) return -1;
    if (*ia > *ib) return 1;
    return 0;
}

static void destroy_int(void *p) {
    free(p);
}

// Helper Function To Copy Room Data From Teh Data Generator Into A Room Struct
static Status loader_copy_room_data(Room *room, const DG_Room *dg_room){
    
    // Get The Floor Grid Generated By The Data Generator
        if(dg_room->floor_grid != NULL){

            int grid_size = dg_room->width * dg_room->height;

            // Allocate Space For A Copy Of The Floor Grid That Can Be Used To Replace The One Generated By The Data Generator Which Will Be Lost After stop_datagen()
            bool *floor_grid_copy = malloc(sizeof(bool) * (grid_size));
            if(floor_grid_copy == NULL){
                return NO_MEMORY;
            }

            // Create A Copy Of The floor_grid Generated By The Data Generator
            for(int i = 0; i < grid_size; i++){
                floor_grid_copy[i] = dg_room->floor_grid[i];
            }

            // Set The Floor Grid
            room_set_floor_grid(room, floor_grid_copy);
        }

        // Get The Pushables Generated By The Data Generator
        if(dg_room->pushable_count > 0){

            // Allocate Space For A Copy Of The Pushables That Can Be Used To Replace The One Generated By The Data Generator Which Will Be Lost After stop_datagen()
            Pushable *pushables = malloc(sizeof(Pushable) * dg_room->pushable_count);
            if(pushables == NULL){
                return NO_MEMORY;
            }

            // Create A Copy Of The Pushables Generated By The Data Generator
            for(int i = 0; i < dg_room->pushable_count; i++){
                pushables[i].id = dg_room->pushables[i].id;
                pushables[i].initial_x = dg_room->pushables[i].x;
                pushables[i].initial_y = dg_room->pushables[i].y;
                pushables[i].x = dg_room->pushables[i].x;
                pushables[i].y = dg_room->pushables[i].y;
            } 

            room->pushables = pushables;
            room->pushable_count = dg_room->pushable_count;
        }

        // Get The Portals Generated By The Data Generator
        if(dg_room->portal_count > 0){

            // Allocate Space For A Copy Of The Portals That Can Be Used To Replace The One Generated By The Data Generator Which Will Be Lost After stop_datagen()
            Portal *portals = malloc(sizeof(Portal) * dg_room->portal_count);
            if(portals == NULL){
                return NO_MEMORY;
            }

            // Create A Copy Of The Portals Generated By The Data Generator
            for(int i = 0; i < dg_room->portal_count; i++){
                portals[i].id = dg_room->portals[i].id;
                portals[i].x = dg_room->portals[i].x;
                portals[i].y = dg_room->portals[i].y;
                portals[i].target_room_id = dg_room->portals[i].neighbor_id;
            }

            // Set The Portals
            room_set_portals(room, portals, dg_room->portal_count);
        }

        // Get The Treasure Generated By The Data Generator
        if(dg_room->treasure_count > 0){

            // Allocate Space For A Copy Of The Treasure That Can Be Used To Replace The One Generated By The Data Generator Which Will Be Lost After stop_datagen()
            Treasure *treasures = malloc(sizeof(Treasure) * dg_room->treasure_count);
            if(treasures == NULL){
                return NO_MEMORY;
            }

            // Create A Copy Of The Treasure Generated By The Data Generator
            for(int i = 0; i < dg_room->treasure_count; i++){
                treasures[i].id = dg_room->treasures[i].global_id;
                treasures[i].x  = dg_room->treasures[i].x;
                treasures[i].y  = dg_room->treasures[i].y;
                treasures[i].collected = false;
            }

            // Set The Treasure
            room_set_treasures(room, treasures, dg_room->treasure_count);
        }

    return OK;
}

Status loader_load_world(const char *config_file, Graph **graph_out, Room **first_room_out, int  *num_rooms_out, Charset *charset_out){

    // Verify All Arguments Are Entered
    if(config_file == NULL || graph_out == NULL || first_room_out == NULL || num_rooms_out == NULL || charset_out == NULL){
        return INVALID_ARGUMENT;
    }

    *graph_out = NULL;
    *first_room_out = NULL;
    *num_rooms_out = 0;

    // Start The Data Generator 
    int status = start_datagen(config_file);

    // Return An Error If The Data Generator Finds The Configure Path Invalid
    if(status == DG_ERR_CONFIG){
        return WL_ERR_CONFIG;
    }

    // Verify The Data Generator Is Successfully Running 
    if(status != DG_OK){
        return WL_ERR_DATAGEN;
    }

    Graph *graph = NULL;

    // Verify The Graph Is Successfully Created 
    if(graph_create(compare_ints, destroy_int, &graph) != GRAPH_STATUS_OK){
        stop_datagen();
        return NO_MEMORY;
    }

    // Get The Charcter Set
    const DG_Charset *charset = dg_get_charset();
    
    // Set All The Charcters In The Charcter Set
    if(charset != NULL){
        charset_out->wall = charset->wall;
        charset_out->floor = charset->floor;
        charset_out->player = charset->player;
        charset_out->pushable = charset->pushable;
        charset_out->treasure = charset->treasure;
        charset_out->portal = charset->portal;
    }

    // Itterated Through Rooms 
    while(has_more_rooms()){
        
        // Get The Next Room
        DG_Room dg_room = get_next_room();

        // Initialize The Room And Verify It Was Successfully Created
        Room *room = room_create(dg_room.id, NULL, dg_room.width, dg_room.height);
        if(room == NULL){
            graph_destroy(graph);
            stop_datagen();
            return NO_MEMORY;
        } 

        // Call Helper Function To Copy The Data Generator's Room Data Into The Room Struct
        Status copy_status = loader_copy_room_data(room, &dg_room);
        if(copy_status != OK){
            room_destroy(room);
            graph_destroy(graph);
            stop_datagen();
            return copy_status;
        }

        // Create A Node On The Graph For The Room
        if(graph_insert(graph, room) != GRAPH_STATUS_OK){
            room_destroy(room);
            graph_destroy(graph);
            stop_datagen();
            return NO_MEMORY;
        }

        // Set The First Room If It Has Not Already Been Set
        if(*first_room_out == NULL){
            *first_room_out = room;
        }

        // Increase The Amount Of Rooms Generated
        (*num_rooms_out)++;
    }

    const void * const *payloads = NULL;
    int payload_count = 0;

    // Get All Payloads
    graph_get_all_payloads(graph, &payloads, &payload_count);

    // Iterate Through All Payloads
    for(int i = 0; i < payload_count; i++){

        Room *from = (Room *)payloads[i];

        // Iterate Through All Portals In The Room
        for(int portal_index = 0; portal_index < from->portal_count; portal_index++){

            // Get The Target Rooms ID
            int target_room_id = from->portals[portal_index].target_room_id;

            // Find The Room The Portal Goes Into
            for(int j = 0; j < payload_count; j++){

                Room *to = (Room *)payloads[j];

                // Conect The Rooms In The Graph If A Portal Connectects The Rooms 
                if(to->id == target_room_id){
                    graph_connect(graph, from, to);
                    break;
                }
            }        
        }
    }

    *graph_out = graph;
    stop_datagen();
    return OK;
}
